### PR TITLE
add flexibility to environment inside namings & fix humidity issue

### PR DESCRIPTION
**Pull request by W-Geronius**
This PR proposes modifications in order to

* fix the humidity vs. relativeHumidity issue
* permit free choice of inside location specifiers
* feed voltage to electrical.batteries.  branch
* ensure paths conforming to schema rules 1.5

Plugin Setup to determine SK paths:

* **Location set to ''**	will generate 'outside.temperature', or 'outside.humidity' ...
* **Location set to 'inside'** will generate 'inside.temperature', or 'inside.relativeHumidity' ...
* **Location set to 'refrigerator'** will generate 'inside.refrigerator.temperature', or 'inside.refrigerator.relativeHumidity' ...

When applying this modifications, previous setups will **not be changed**, but internally stripped of any included dots. These values will show up in inside path. It is strongly advised however to visit the setup page after install

pluginConfig

### CODE REVIEW

**Comment by vokkim** [comment]
I merged your PR with some modifications inspired by PR from @hkapanen. However I could not test these changes, since I don't have any RuuviTags with me at the moment so I hope it works :)

**Comment by ghost** [comment]
I had the chance to test the PR on a live system. Still running. No problems encountered. And it basically fulfilled my feature request (closed by myself).Thanks to @W-Geronius and @vokkim

**Comment by W-Geronius** [comment]
Sorry to say, Mikko, but with the other changes the initial error was reintroduced. According to SK specs, in outside branch it must be named '**humidity**' and in insidebranch it must be named '**relativeHumidity**'. Now the plugin would produce 'environment.outside.relativeHumidity'. 

Additionally:  the new location pattern `[a-zA-Z0-9]+(\.[a-zA-Z0-9])*` would allow invalid paths as well as multiple subpaths, conflicting with SK schema

**Comment by vokkim** [comment]
And sorry for that, tried to fix it now in `1.2.3` but still coding blind. This plugin would need tests (*wink*), wish I had the time!

**Comment by W-Geronius** [comment]
I sure can test by code inspection and with ruuvitag  - from what I saw in the code, it would just be necessary to merge the new 'try - catch' thing to my PR code. I know my approach looks complicated, but it's required because of the unfortunate SK schema rules ;)

**Pull request merged**
